### ISSUE TITLE
units not converted properly

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#338] opened 2015-08-13 17:07 UTC
Major major bug. I'm surprised our unit tests didn't catch this.

First I'll show the correct behavior. Here's a simple GP, run on an old version of GPkit:

```python
from gpkit import Variable, GP
x = Variable('x', value=3, units="ft")
y = Variable('y', units="m")
prob = GP(y, [y == x])
sol = prob.solve()
print sol.table()
```
`x` is in feet; `y` is in meters. The solution gets it right:
```

Using solver 'cvxopt'
Solving for 1 variables.
Solving took 0.00434 seconds.

Cost
----
 0.9144 [m] 

Free variables
--------------
y : 0.9144  [m] 

Swept variables
---------------

Constants
---------
x : 3  [ft] 

Constant and swept variable sensitivities
-----------------------------------------
x : 1 
```

And now for the same thing, run on the current master:
```python
from gpkit import Variable, Model
x = Variable('x', value=3, units="ft")
y = Variable('y', units="m")
prob = Model(y, [y == x])
sol = prob.solve()
```
```

Using solver 'cvxopt'
Solving for 1 variables.
Solving took 0.0053 seconds.

Cost
----
 3 [m] 

Free Variables
--------------
y : 3  [m] 

Constants
---------
x : 3  [ft] 

Sensitivities
-------------
x : 1 
```
(hmm, 3 meters does not equal 3 feet).

@bqpd, aside from fixing this, what's the best targeted unit test for this?

**Comment by whoburg** [comment] 2015-08-13 17:15
- [ ] fix
 - [ ] add targeted unit tests for unit conversion
 - [ ] clarify somewhere exactly where unit conversions happen -- if I'm looking at the `cs` of a (nomial, GP, or Model), is it the `c` before or after units are converted?

**Comment by bqpd** [comment] 2015-08-13 17:21
There is supposed to be a test for this...`simpleflight`. Hmm.

**Comment by bqpd** [comment] 2015-08-13 18:13
Weird, the constraint is right...

**Comment by whoburg** [comment] 2015-08-13 18:15
`mmaps`?

**Comment by bqpd** [comment] 2015-08-13 18:17
Haha, I don't think so. the `gp` is wrong.

**Comment by bqpd** [comment] 2015-08-13 18:20
`(y==x).c # 0.3048`

**Comment by bqpd** [comment] 2015-08-13 18:20
The problem is in the generation of prob.unsubbed_cs?

**Comment by bqpd** [comment] 2015-08-13 18:22
It's in the creation of the equality constraint, that's probably why it didn't show in `simpleflight`

**Comment by bqpd** [comment] 2015-08-13 18:23
It's in the declaration of `leq` and `geq`

**Comment by bqpd** [comment] 2015-08-13 18:23
```python
In [11]: (y==x).leq
Out[11]: gpkit.Monomial(x**-1*y [m/ft])
```

**Comment by bqpd** [comment] 2015-08-13 18:24
Yeahhh all that unit-conversion stuff in Constraint was there for a reason.

**Comment by bqpd** [comment] 2015-08-13 18:39
The problem with unit conversions was that Pint is happy to let the units be `ft/m` unless prodded to convert them to "dimensionless". In constraints that currently happens in __init__, but I'll try adding it to Signomial.__init__

**Comment by bqpd** [comment] 2015-08-13 18:49
Yeah, doing that makes it a one-line fix.

**Comment by whoburg** [comment] 2015-08-13 19:16
I guess this might be partially my fault for doing f7c2196f1a2f132b3d163587075261f04a6c3eb2... ?

**Comment by bqpd** [comment] 2015-08-14 00:04
Haha. It should have been fixed in the Signomial __init__ anyway.

**Closed** 2015-08-14 02:32 UTC
Labels: bug, waiting on PR

**Comment by whoburg** [comment] 2015-08-14 02:54
Since the item copied below is checked off, where can I read about it?

``clarify exactly where unit conversions happen -- if I'm looking at the cs of a (nomial, GP, or Model), is it the c before or after units are converted?''

**Comment by bqpd** [comment] 2015-08-14 03:20
Oops, sorry. Unit conversions/coercions happen in substitutions and simplifications, so that c is _after_ untis are conveted. Prior to this issue, there was a bug where units that were dimensionless such as [ft/m]) were not coerced to be the specific [dimensionless] unit during the creation of a Signomial, and so trapped the conversion multiplier. Pints, man.

**Comment by whoburg** [comment] 2015-08-14 12:41
ok, makes a lot of sense. thanks.
