### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#193] opened 2015-04-14 17:12 UTC
```
JPM:~ janellemansfield$ pip install ctypesgen --pre
Downloading/unpacking ctypesgen
 Cannot fetch index base URL https://pypi.python.org/simple/
 Could not find any downloads that satisfy the requirement ctypesgen
Cleaning up...
No distributions at all found for ctypesgen
Storing debug log for failure in /var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/tmpy2imSj
```

**Comment by cjk12** [comment] 2015-04-14 17:13
@jpmjanelle was trying to install Anaconda and got this...

**Comment by bqpd** [comment] 2015-04-14 17:15
This was run after installing anaconda? Hmm. What platform?

**Comment by bqpd** [comment] 2015-04-14 17:15
Also, run `pip --version`

**Comment by cjk12** [comment] 2015-04-14 17:26
Mac OS 10.8.5.  It's Moutain Lion.

On Tue, Apr 14, 2015 at 1:15 PM, bqpd <notifications@github.com> wrote:

> Also, run pip --version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/convexopt/gpkit/issues/193#issuecomment-92985361>.
>



-- 
*Cody J. Karcher*
Graduate Student
Department of Aeronautics and Astronautics
Massachusetts Institute of Technology

**Comment by jpmjanelle** [comment] 2015-04-14 17:27
I have pip 1.5.1 and python 2.7

**Comment by bqpd** [comment] 2015-04-14 17:31
Try updating pip with `pip install pip --upgrade` (may need sudo) and then installing ctypesgen?

**Comment by bqpd** [comment] 2015-04-14 17:32
Hmm, looking at the error message: `Cannot fetch index base URL https://pypi.python.org/simple/`. I wonder if your pip install is having trouble accessing the internet?

**Comment by jpmjanelle** [comment] 2015-04-14 17:58
I reconnected to the internet, and I no longer get that message. But now I get another error: 
```
JPM:~ janellemansfield$ pip install ctypesgen --pre
Downloading/unpacking ctypesgen
  Downloading ctypesgen-0.r125.tar.gz (105kB): 105kB downloaded
  Running setup.py (path:/private/var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/pip_build_janellemansfield/ctypesgen/setup.py) egg_info for package ctypesgen
    
Installing collected packages: ctypesgen
  Running setup.py install for ctypesgen
    changing mode of build/scripts-2.7/ctypesgen.py from 644 to 755
    error: could not create '/Library/Python/2.7/site-packages/ctypesgencore': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/pip_build_janellemansfield/ctypesgen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/pip-luPEtg-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/ctypesgencore

copying ctypesgencore/__init__.py -> build/lib/ctypesgencore

copying ctypesgencore/ctypedescs.py -> build/lib/ctypesgencore

copying ctypesgencore/descriptions.py -> build/lib/ctypesgencore

copying ctypesgencore/expressions.py -> build/lib/ctypesgencore

copying ctypesgencore/libraryloader.py -> build/lib/ctypesgencore

copying ctypesgencore/messages.py -> build/lib/ctypesgencore

copying ctypesgencore/old libraryloader.py -> build/lib/ctypesgencore

copying ctypesgencore/options.py -> build/lib/ctypesgencore

creating build/lib/ctypesgencore/parser

copying ctypesgencore/parser/__init__.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/cdeclarations.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/cgrammar.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/cparser.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/ctypesparser.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/datacollectingparser.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/lex.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/lextab.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/parsetab.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/pplexer.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/preprocessor.py -> build/lib/ctypesgencore/parser

copying ctypesgencore/parser/yacc.py -> build/lib/ctypesgencore/parser

creating build/lib/ctypesgencore/printer

copying ctypesgencore/printer/__init__.py -> build/lib/ctypesgencore/printer

copying ctypesgencore/printer/defaultheader.py -> build/lib/ctypesgencore/printer

copying ctypesgencore/printer/preamble.py -> build/lib/ctypesgencore/printer

copying ctypesgencore/printer/printer.py -> build/lib/ctypesgencore/printer

copying ctypesgencore/printer/test.py -> build/lib/ctypesgencore/printer

creating build/lib/ctypesgencore/processor

copying ctypesgencore/processor/__init__.py -> build/lib/ctypesgencore/processor

copying ctypesgencore/processor/dependencies.py -> build/lib/ctypesgencore/processor

copying ctypesgencore/processor/operations.py -> build/lib/ctypesgencore/processor

copying ctypesgencore/processor/pipeline.py -> build/lib/ctypesgencore/processor

running build_scripts

creating build/scripts-2.7

copying and adjusting ctypesgen.py -> build/scripts-2.7

changing mode of build/scripts-2.7/ctypesgen.py from 644 to 755

running install_lib

creating /Library/Python/2.7/site-packages/ctypesgencore

error: could not create '/Library/Python/2.7/site-packages/ctypesgencore': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/pip_build_janellemansfield/ctypesgen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/pip-luPEtg-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/pip_build_janellemansfield/ctypesgen
Storing debug log for failure in /var/folders/nx/sxj_gc093xs4nyg3qndh1zyr0000gn/T/tmpgBXCOD
```

**Comment by jpmjanelle** [comment] 2015-04-14 17:59
I think the problem is coming from this
```
error: could not create '/Library/Python/2.7/site-packages/ctypesgencore': Permission denied
```

**Comment by bqpd** [comment] 2015-04-14 18:04
Try `sudo pip install ctypesgen --pre` (or make a virtual environment so that you don't need sudo.)

**Comment by jpmjanelle** [comment] 2015-04-14 18:37
Thanks ned! that worked for me. 

Now I'm having another issue. I finished the install instructions and ran `python -c "import gpkit.tests; gpkit.tests.run()"` and got these errors:

```
======================================================================
ERROR: test_call (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/gpkit/tests/t_gp_solution_array.py", line 12, in test_call
    sol = prob.solve(printing=False)
  File "//anaconda/lib/python2.7/site-packages/gpkit/geometric_program.py", line 224, in solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR: test_call_vector (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/gpkit/tests/t_gp_solution_array.py", line 20, in test_call_vector
    sol = prob.solve(printing=False)
  File "//anaconda/lib/python2.7/site-packages/gpkit/geometric_program.py", line 224, in solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

----------------------------------------------------------------------
Ran 29 tests in 0.160s
```

**Comment by bqpd** [comment] 2015-04-14 18:38
It looks like `build.py` hasn't been run. Did you install gpkit via pip, or via the github repository?

**Comment by jpmjanelle** [comment] 2015-04-14 18:38
I installed it via pip, should I try it through github?

**Comment by bqpd** [comment] 2015-04-14 18:39
No, it should have work through pip. Try `sudo pip install gpkit --upgrade` and paste the output?

**Comment by jpmjanelle** [comment] 2015-04-14 18:39
```
Requirement already up-to-date: gpkit in /anaconda/lib/python2.7/site-packages
Requirement already up-to-date: numpy in /anaconda/lib/python2.7/site-packages (from gpkit)
Collecting ctypesgen>=0.r125 (from gpkit)
  Downloading ctypesgen-0.r125.tar.gz (105kB)
    100% |################################| 106kB 660kB/s 
    //anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/setuptools/dist.py:282: UserWarning: Normalizing '0.r125' to '0.post125'
  Requested ctypesgen>=0.r125 (from gpkit), but installing version 0.post125
Installing collected packages: ctypesgen
  Found existing installation: ctypesgen 0.post125
    Uninstalling ctypesgen-0.post125:
      Successfully uninstalled ctypesgen-0.post125
  Running setup.py install for ctypesgen
    //anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/setuptools/dist.py:282: UserWarning: Normalizing '0.r125' to '0.post125'
    changing mode of build/scripts-2.7/ctypesgen.py from 644 to 755
    changing mode of //anaconda/bin/ctypesgen.py to 755
Successfully installed ctypesgen-0.post125
```

**Comment by bqpd** [comment] 2015-04-14 18:40
That's it installing `ctypesgen`...is not not running `gpkit/setup.py`?

**Comment by jpmjanelle** [comment] 2015-04-14 18:41
I don't think so, that is the only output I get

**Comment by bqpd** [comment] 2015-04-14 18:42
Huh! Okay, looks like pip isn't running the gpkit setup script. Odd.

**Comment by bqpd** [comment] 2015-04-14 18:44
Testing on my computer, but it's taking a little bit. Are you on campus?

**Comment by bqpd** [comment] 2015-04-14 18:45
Oh, did you install any solvers?

**Comment by jpmjanelle** [comment] 2015-04-14 18:46
I installed mozek. Yes I am on campus, do you want me to come by?

**Comment by bqpd** [comment] 2015-04-14 18:46
Sure! I'm in 3-446, or could meet you somewhere else.

**Comment by jpmjanelle** [comment] 2015-04-14 18:51
Okay, I can come by in 10 min!

**Comment by bqpd** [comment] 2015-04-14 19:38
Closed in person.

**Closed by bqpd** 2015-04-14 19:38 UTC
