### ISSUE TITLE
Incorrect cost for simple GP -- possible mosek bug

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#296] opened 2015-07-22 20:10 UTC
The optimal cost for this GP should be 3, but instead it is 2.889

```
from gpkit import Variable, GP

x1 = Variable('x1')
x2 = Variable('x2')

gp = GP(1.+ x1 + x2, [x1 >= 1., x2 >=1.])
sol = gp.solve(solver="mosek")
print sol.table()
```

```
In [1]: %run debug2.py
Optional Python units library (Pint) not installed; unit support disabled.
Using solver 'mosek'
Solving for 2 variables.
Solving took 0.0148 seconds.

Cost
----
 2.889

Free variables
--------------
x1 : 1 
x2 : 1 

Swept variables
---------------

Constants
---------

Constant and swept variable sensitivities
-----------------------------------------

```

**Comment by whoburg** [comment] 2015-07-22 20:17
Wow, that's not good.

Reproduced -- appears to only occur for MOSEK.

This urgently needs to become fixed, and also become a unit test.

**Comment by bqpd** [comment] 2015-07-22 20:22
The error is the incorrect cost?

**Comment by bqpd** [comment] 2015-07-22 20:22
(unrelatedly, we should stop printing tables that are blank...)

**Comment by whoburg** [comment] 2015-07-22 20:28
Correct, variable values appear correct; just the cost seems incorrect. (haven't looked at sensitivites).

Agreed on not printing blanks.

**Comment by whoburg** [comment] 2015-07-22 20:29
And we should consider internally checking (on every solve) that the solution substituted into the objective equals the cost reported by the solver.

**Comment by bqpd** [comment] 2015-07-22 20:30
We did at one point, it was just disabled for speed reasons. (there's a few issues floating around about doing this right)

**Comment by pgkirsch** [comment] 2015-07-24 16:05
Forgot about this issue, working on it now

**Comment by pgkirsch** [comment] 2015-07-24 18:08
So I don't know *why* it's happening, but I have a better idea about *what* is happening.

Consider an even simpler version of the original problem:

```
x1 = Variable('x1')
gp = GP(1. + x1, [x1 >= 10.])
sol = gp.solve(solver="mosek")
print sol.table()
```

The optimal cost should obviously be `11`, but instead we get `14.45`.
If we tweak the lower bound as such
```
gp = GP(1. + x1, [x1 >= 100.])
```
we get a solution of `144.5` instead of `101`.  You can change it a few more times to see that each time the optimal cost is just `1.445 * optimal_x1`.

Now, if we change the *constant* value from `1` to `2`, we find that the optimal cost is now `2.087 * optimal_x1` for any choice of lower bound. Repeating this for a few more values, we get:

constant | multiplier
------------ | ------------
1 | 1.445
2 | 2.087
5 | 6.293
10 | 39.6

And if you look closer:
```
1.445^2 = 2.08
1.445^5 = 6.29
1.445^10 = 39.6
```
etc.

**Comment by pgkirsch** [comment] 2015-07-24 18:13
As another test I've done is to look at three ways of doing the same thing:
```
x1 = Variable('x1')
gp = GP(2. + x1, [x1 >= 10.])
```

```
x0 = Variable('x0', value=1)
x1 = Variable('x1')
gp = GP(2.*x0 + x1, [x1 >= 10.])
```

```
x0 = Variable('x0')
x1 = Variable('x1')
gp = GP(x0 + x1, [x0 >= 2, x1 >= 10.])
```

Only the third method gets the desired result, the first two both give an optimal cost of `20.87`.

**Comment by pgkirsch** [comment] 2015-07-24 18:15
It seems as though `c`, `A`, and `p_idx` are all being passed correctly to `expopt.imize` as you'd probably expect given that this is only failing for mosek. Could this just be a mosek bug?

**Comment by bqpd** [comment] 2015-07-24 18:26
I hope it's just a mosek-parsing bug in the return statement of
expopt.imize.

**Comment by pgkirsch** [comment] 2015-07-24 18:33
Oh well I'm afraid it isn't that because

```
        r = MSK._expoptimize(expopttask,
                             ptr(prosta),
                             ptr(solsta),
                             ptr(objval),
                             ptr(xx),
                             ptr(yy),
                             ptr_expopthnd)
 
       print objval.value
       # 14.4466786101
       # should be 11
```

**Comment by bqpd** [comment] 2015-07-24 18:59
Alack.

**Comment by pgkirsch** [comment] 2015-07-24 18:59
Maybe it's fair (for the objective function *only*) to require every monomial in a posynomial to contain a variable? Thoughts @whoburg?

**Comment by bqpd** [comment] 2015-07-24 19:46
I'd rather strip out the constant term before solving and add it back in later.

**Comment by pgkirsch** [comment] 2015-07-24 19:58
That seems like a nice enough solution, I'll work on it

**Comment by bqpd** [comment] 2015-07-24 20:00
Do it in expopt.imize, so that the solver interface doesn't have to worry about that junk.

Does this happen with `mosek_cli` as well?

**Comment by pgkirsch** [comment] 2015-07-24 20:01
Sounds good. 

And yes.

**Comment by bqpd** [comment] 2015-07-24 20:16
* sighs *

**Comment by pgkirsch** [comment] 2015-07-24 21:19
what is `k` in expopt.imize?

**Comment by whoburg** [comment] 2015-07-24 22:11
Really, a true mosek bug? This seems quite shocking.

Surely their documentation has some really simple GPs where they inspect the resulting cost. We should try to reproduce using one of those.

(It's ok to hot fix this for 0.2.0, but once a patch is in place let's leave the ticket open with a later milestone to dig a little deeper.)

**Comment by pgkirsch** [comment] 2015-07-24 22:13
The problem with stripping out the constant term inside `expopt.imize` is that things like `c` and `p_idxs` are unchanged in `_parse_result()` and the solver returns a shorter `xx` and `yy` which makes for unhappiness all round.

One possibly (hacky) fix is to divide the answer by `1.44466786101**c[0]`. It seems to work very well.

**Comment by pgkirsch** [comment] 2015-07-24 22:13
Oh just kidding, it breaks for a big c[0] (anything over 1000)

**Comment by pgkirsch** [comment] 2015-07-24 22:14
I tried finding a really simple example in the expopt documentation but couldn't. I'll look again.

**Comment by pgkirsch** [comment] 2015-07-24 22:15
Another proposed solution is to send it to the solver twice, once without the constant and once with and mix and match the results from the two (i.e. objective function from without, xx and yy from with). It's gross but would probably work.

**Comment by whoburg** [comment] 2015-07-24 22:17
For the hot fix, what if we just compute the cost by substituting the solution (primal variables) into the objective?

**Comment by pgkirsch** [comment] 2015-07-24 22:18
The only other option I can think of it is to add a placeholder variable to the A matrix, which doesn't exactly sound like a fund time.

**Comment by pgkirsch** [comment] 2015-07-24 22:19
+1 for really, really simple/obvious solution. on it.

**Comment by whoburg** [comment] 2015-07-24 22:21
Make sure some or all of the examples above get added to the unit tests.

The current unit tests in `t_geometric_program` should also be modified -- add lines to test `sol["cost"]` for some of the current examples, especially `test_trivial_gp` and `test_trivial_vector_gp`

**Comment by whoburg** [comment] 2015-07-27 01:04
Update: this issue was patched in f51d12b13450caee8103969161cdec3175570c71 -- specifically in `GeometricProgram._parse_result`.

Still need to determine why mosek is returning incorrect objective value!

**Comment by bqpd** [comment] 2015-08-10 18:21
I still think this should be patched in the mosek solvers, not in parse_result.

**Comment by whoburg** [comment] 2015-08-11 03:32
I agree with that as a long term solution, if this is really a mosek bug. I remain mildly skeptical that it's a real mosek bug, especially with issues like #313 and some A matrix transpose confusion still floating around.

But I'm willing to be convinced, at which point I'll agree with moving the fix to the mosek solvers.

**Comment by bqpd** [comment] 2015-08-11 04:25
I think both of those are fixed in the refactor!

**Comment by bqpd** [comment] 2015-08-11 05:02
Looking in the [MOSEK GP documentation](http://docs.mosek.com/7.1/capi/Exponential_optimization.html), their example does not have a constant in the cost function...

**Comment by pgkirsch** [comment] 2015-08-11 05:13
Yes! That was what I was saying in the discussion for PR #304. I don't think it's a bug, I just don't think they support having a constant in the cost function.

**Comment by bqpd** [comment] 2015-08-11 05:14
Which is kinda weird. But consistent across the CLI and the C interface.

**Comment by whoburg** [comment] 2015-08-11 15:00
I disagree -- I think the mosek API does handle constants in the cost function, and the c function `mskexpopt` seems to be working properly. (still willing to be convinced, but here's my evidence):

1. The documentation linked above seems to include the constants in the objective case just fine (just make a term with a `c_k` equal to the constant and `a_k,j` equal to zero).

2. Here's the mosek expopt example, slightly modified to include a constant term in the objective equal to 100. This should therefore increase the objective value of the solution by 100:

file expopt1_mod.eo
```
* File : expopt1.eo

1   * numcon
3   * numvar
6   * numter

* Coefficients of terms

40           
20
40
100
0.3333333
1.3333333

* For each term, the index of the 
* constraints to the term belongs

0     
0
0
0
1
1

* Section defining a_kj

0 0 -1
0 1 -0.5
0 2 -1
1 0 1.0
1 2 1.0
2 0 1.0
2 1 1.0
2 2 1.0
3 0 0   * 4th objective term does not depend on any variables
4 0 -2
4 1 -2
5 1 0.5
5 2 -1.0
```

Run this (`./mskexpopt expopt1_mod.eo`)
In comparison with their solution, which has an objective value of 1.331371e+02, the modified one is indeed 1e2 larger.

```
Expopt solution summary:
PROBLEM STATUS      : PRIMAL_AND_DUAL_FEASIBLE
Solution status     : OPTIMAL
Primal - objective  : 2.3313707802e+02
```

So, I still think gpkit might be handling constants in objectives incorrectly, prior to passing to mosek.

**Comment by pgkirsch** [comment] 2015-08-11 17:32
That's pretty solid evidence, hard to argue with it....

**Comment by pgkirsch** [comment] 2015-08-11 19:09
Identified the problem (passing incorrect arrays for `subj`, `subk`, and `akj` to the solver) and you are absolutely right. Working on a fix now.

**Comment by whoburg** [comment] 2015-08-11 19:11
@pgkirsch if I were debugging this I would start by determining the Model.problem.A and model.problem.cs and model.problem.p_idxs, and see if they look correct. Then I would probably hard code those to a `.eo` file, like the above, and see whether mosek running the `.eo` file at the command line has the same behavior as gpkit's expoptimize function.

**Comment by whoburg** [comment] 2015-08-11 19:11
Awesome!! disregard my last comment.

**Comment by pgkirsch** [comment] 2015-08-11 20:10
For the original test case (`gp = Model(1.+ x1 + x2, [x1 >= 1., x2 >=1.])`), the `self.exps` in GeometricProgram.__init__ (sidetone: I thought GP was being deprecated) looks as follows:

```
> self.exps
({}, {x1: 1}, {x2: 1}, {x1: -1}, {x2: -1})
```

Without something in that first dict, it is going to be difficult to make the correct `A` matrix, but without any variables to use as varkeys, then I'm not sure how that first dict is going to look correct. I feel like this is going to be a somewhat substantial fix, so does anyone have any thoughts on a preferred approach?

Possible (inelegant solutions):
- Some kind of placeholder variable to use as a var key
- Something that identifies when `p_idxs` and/or `cs` is longer than `A.rows` and prepends some zeros to fix the A matrix.

**Comment by whoburg** [comment] 2015-08-11 20:22
Those `exps` seem right to me.

Is the fix as simple as inserting a zero exponent for *any* variable when there is an empty dict in exps? That's what I did in my command-line example...

@bqpd

**Comment by whoburg** [comment] 2015-08-11 20:23
What's the current `A` matrix and `cs` and `p_idxs` for the original example?

**Comment by bqpd** [comment] 2015-08-11 20:25
@whoburg, that sounds reasonable.

**Comment by pgkirsch** [comment] 2015-08-11 20:26
```
c:
[ 1.  1.  1.  1.  1.]

p_idxs:
[0 0 0 1 2]

A:
CootMatrix(row=[2, 4, 1, 3], col=[0, 0, 1, 1], data=[1, -1, 1, -1])

(should be CootMatrix(row=[0, 2, 4, 1, 3], col=[0, 0, 0, 1, 1], data=[0, 1, -1, 1, -1]))
```

**Comment by bqpd** [comment] 2015-08-11 20:28
Ooh let me try something.

**Comment by bqpd** [comment] 2015-08-11 20:29
Bingo.

**Comment by pgkirsch** [comment] 2015-08-11 20:42
Sooo.... this issue is closed?

**Comment by pgkirsch** [comment] 2015-08-11 20:47
Github should at least give assists, for when @bqpd steals all my goals.

**Comment by bqpd** [comment] 2015-08-11 20:48
You guys figured it out, I just coded it. :p

**Comment by pgkirsch** [comment] 2015-08-11 20:48
I will write a unit test for this, unless of course @bqpd wants to swoop in and write a much better one in about a tenth of the time.

**Comment by bqpd** [comment] 2015-08-11 20:51
The issue will close on merging the refactor.
@whoburg wrote some tests in `t_model.py`, line 170.
I found you a trophy, though!
![assist trophy](http://www.lfp.fr/trophee/trophee_passeur_L2_hdef.jpg)

**Comment by pgkirsch** [comment] 2015-08-11 20:52
I hate everything

**Comment by bqpd** [comment] 2015-08-11 20:53
Is it because it's a French trophy.

**Comment by whoburg** [comment] 2015-08-11 21:19
Lol. Great work guys! Nice job both of you on debugging, finding the issue, and fixing it right.

**Closed** 2015-08-11 21:45 UTC
Labels: in progress
