### ISSUE TITLE
Tests fail on fresh install

### ISSUE THREAD

**Issue by cfrontin** [convexopt/gpkit#385] opened 2015-09-03 15:32 UTC
After following installation instructions, selected tests fail. Error traceback indicates on all errors a problem with operand assignments:

'''shell
Corys-MacBook-Pro:Graduate Research coryfrontin$ python -c "import gpkit.tests; gpkit.tests.run()"
test_composite_objective (gpkit.tests.t_tools.TestMathModels) ... ERROR
test_te_exp_minus1 (gpkit.tests.t_tools.TestMathModels)
Test Taylor expansion of e^x - 1 ... ERROR
test_zero_lower_unbounded (gpkit.tests.t_tools.TestMathModels) ... ok
test_basic (gpkit.tests.t_sub.TestNomialSubs)
Basic substitution, symbolic ... ok
test_dimensionless_units (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_numeric (gpkit.tests.t_sub.TestNomialSubs)
Basic substitution of numeric value ... ok
test_scalar_units (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_string_mutation (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_variable (gpkit.tests.t_sub.TestNomialSubs)
Test special single-argument substitution for Variable ... ok
test_vector (gpkit.tests.t_sub.TestNomialSubs) ... ERROR
test_vector_init (gpkit.tests.t_sub.TestGPSubs) ... ok
test_vector_sweep (gpkit.tests.t_sub.TestGPSubs) ... ok
test_dict_key (gpkit.tests.t_vars.TestVarKey)
make sure variables are well-behaved dict keys ... ok
test_eq_neq (gpkit.tests.t_vars.TestVarKey)
Test boolean equality operators ... ok
test_init (gpkit.tests.t_vars.TestVarKey)
Test VarKey initialization ... ok
test_repr (gpkit.tests.t_vars.TestVarKey)
Test __repr__ method ... ok
test_units_attr (gpkit.tests.t_vars.TestVarKey)
Make sure VarKey objects have a units attribute ... ok
test_init (gpkit.tests.t_vars.TestVariable)
Test Variable initialization ... ok
test_value (gpkit.tests.t_vars.TestVariable)
Detailed tests for value kwarg of __init__ ... ok
test_init (gpkit.tests.t_vars.TestVectorVariable)
Test VectorVariable initialization ... ERROR
test_is_vector_variable (gpkit.tests.t_vars.TestArrayVariable) ... ok
test_str (gpkit.tests.t_vars.TestArrayVariable)
Make sure string looks something like a numpy array ... ok
test_constraint_gen (gpkit.tests.t_nomials.TestPosynomial)
Test creation of Constraints via operator overloading ... ok
test_diff (gpkit.tests.t_nomials.TestPosynomial)
Test differentiation (!!) ... ok
test_init (gpkit.tests.t_nomials.TestPosynomial)
Test Posynomial construction ... ok
test_integer_division (gpkit.tests.t_nomials.TestPosynomial)
Make sure division by integer doesn't use Python integer division ... ok
test_monoapprox (gpkit.tests.t_nomials.TestPosynomial)
Test monomial approximation ... ok
test_posyposy_mult (gpkit.tests.t_nomials.TestPosynomial)
Test multiplication of Posynomial with Posynomial ... ok
test_simplification (gpkit.tests.t_nomials.TestPosynomial)
Make sure like monomial terms get automatically combined ... ok
test_div (gpkit.tests.t_nomials.TestMonomial)
Test Monomial division ... ok
test_eq_ne (gpkit.tests.t_nomials.TestMonomial)
Test equality and inequality comparators ... ok
test_init (gpkit.tests.t_nomials.TestMonomial)
Test multiple ways to create a Monomial ... ok
test_latex (gpkit.tests.t_nomials.TestMonomial)
Test latex string creation ... ok
test_mul (gpkit.tests.t_nomials.TestMonomial)
Test monomial multiplication ... ok
test_numerical_precision (gpkit.tests.t_nomials.TestMonomial)
not sure what to test here, placeholder for now ... ok
test_pow (gpkit.tests.t_nomials.TestMonomial)
Test Monomial exponentiation ... ok
test_repr (gpkit.tests.t_nomials.TestMonomial)
Simple tests for __repr__, which prints more than str ... ok
test_str_with_units (gpkit.tests.t_nomials.TestMonomial)
Make sure __str__() works when units are involved ... ok
test_init (gpkit.tests.t_nomials.TestSignomial)
Test Signomial construction ... ok
test_additive_scalar (gpkit.tests.t_constraints.TestConstraint)
Make sure additive scalars simplify properly ... ok
test_additive_scalar_gt1 (gpkit.tests.t_constraints.TestConstraint)
1 can't be greater than (1 + something positive) ... ok
test_init (gpkit.tests.t_constraints.TestConstraint)
Test Constraint __init__ ... ok
test_oper_overload (gpkit.tests.t_constraints.TestConstraint)
Test Constraint initialization by operator overloading ... ok
test_inheritance (gpkit.tests.t_constraints.TestMonoEQConstraint)
Make sure MonoEQConstraint inherits from the right things ... ok
test_init (gpkit.tests.t_constraints.TestMonoEQConstraint)
Test initialization via both operator overloading and __init__ ... ok
test_non_monomial (gpkit.tests.t_constraints.TestMonoEQConstraint)
Try to initialize a MonoEQConstraint with non-monomial args ... ok
test_array_mult (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_constraint_gen (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_elementwise_mult (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_empty (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_getitem (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_left_right (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_ndim (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_outer (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_prod (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_shape (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_substition (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_sum (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_units (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_additive_constants (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_constants_in_objective_1 (gpkit.tests.t_model.TestGP_cvxopt)
Issue 296 ... ok
test_constants_in_objective_2 (gpkit.tests.t_model.TestGP_cvxopt)
Issue 296 ... ok
test_feasibility_gp_ (gpkit.tests.t_model.TestGP_cvxopt) ... ERROR
test_mdd_example (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_simple_united_gp (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_simpleflight (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_singular (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_terminating_constant_ (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_trivial_gp (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_trivial_vector_gp (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_zeroing (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_issue180 (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_relaxation (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_signomials_not_allowed_in_objective (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_small_signomial (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_trivial_sp (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_trivial_sp2 (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_call (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_call_time (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_call_vector (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_subinto_senssubinto (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_table (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_nan_printing (gpkit.tests.t_solution_array.TestResultsTable)
Test that solution prints when it contains nans ... ok
test_init (gpkit.tests.t_small.TestHashVector)
Make sure HashVector acts like a dict ... ok
test_mul_add (gpkit.tests.t_small.TestHashVector)
Test multiplication and addition ... ok
test_neg (gpkit.tests.t_small.TestHashVector)
Test negation ... ok
test_pow (gpkit.tests.t_small.TestHashVector)
Test exponentiation ... ok

======================================================================
ERROR: test_composite_objective (gpkit.tests.t_tools.TestMathModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_tools.py", line 17, in test_composite_objective
    obj = composite_objective(L+W, W**-1 * L**-3, sub={L: 1, W: 1})
  File "/Library/Python/2.7/site-packages/gpkit/tools.py", line 70, in composite_objective
    w_s = normalization[-1]*PosyArray(w_s)*objectives[-1]
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR: test_te_exp_minus1 (gpkit.tests.t_tools.TestMathModels)
Test Taylor expansion of e^x - 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_tools.py", line 48, in test_te_exp_minus1
    self.assertEqual(te_exp_minus1(y, 1), y)
  File "/Library/Python/2.7/site-packages/gpkit/tools.py", line 40, in te_exp_minus1
    res += posy**i / factorial_denom
TypeError: unsupported operand type(s) for +=: 'int' and 'PosyArray'

======================================================================
ERROR: test_vector (gpkit.tests.t_sub.TestNomialSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_sub.py", line 72, in test_vector
    self.assertTrue(all(p.sub({x: 1, "y": 2}) == 2*z))
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR: test_init (gpkit.tests.t_vars.TestVectorVariable)
Test VectorVariable initialization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_vars.py", line 105, in test_init
    v_mult = 3*v
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR: test_feasibility_gp_ (gpkit.tests.t_model.TestGP_cvxopt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_model.py", line 195, in test_feasibility_gp_
    fgp = gp.feasibility_search(flavour="product")
  File "/Library/Python/2.7/site-packages/gpkit/geometric_program.py", line 290, in feasibility_search
    (1/slackvars).tolist() +  # slackvars > 1
TypeError: unsupported operand type(s) for /: 'int' and 'PosyArray'

----------------------------------------------------------------------
Ran 88 tests in 1.886s

FAILED (errors=5)

######################################################################
Running with units disabled:
EE.......E.........E..........................................E.........................
======================================================================
ERROR: test_composite_objective (gpkit.tests.t_tools.TestMathModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_tools.py", line 17, in test_composite_objective
    obj = composite_objective(L+W, W**-1 * L**-3, sub={L: 1, W: 1})
  File "/Library/Python/2.7/site-packages/gpkit/tools.py", line 70, in composite_objective
    w_s = normalization[-1]*PosyArray(w_s)*objectives[-1]
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR: test_te_exp_minus1 (gpkit.tests.t_tools.TestMathModels)
Test Taylor expansion of e^x - 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_tools.py", line 48, in test_te_exp_minus1
    self.assertEqual(te_exp_minus1(y, 1), y)
  File "/Library/Python/2.7/site-packages/gpkit/tools.py", line 40, in te_exp_minus1
    res += posy**i / factorial_denom
TypeError: unsupported operand type(s) for +=: 'int' and 'PosyArray'

======================================================================
ERROR: test_vector (gpkit.tests.t_sub.TestNomialSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_sub.py", line 72, in test_vector
    self.assertTrue(all(p.sub({x: 1, "y": 2}) == 2*z))
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR: test_init (gpkit.tests.t_vars.TestVectorVariable)
Test VectorVariable initialization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_vars.py", line 105, in test_init
    v_mult = 3*v
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR: test_feasibility_gp_ (gpkit.tests.t_model.TestGP_cvxopt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gpkit/tests/t_model.py", line 195, in test_feasibility_gp_
    fgp = gp.feasibility_search(flavour="product")
  File "/Library/Python/2.7/site-packages/gpkit/geometric_program.py", line 290, in feasibility_search
    (1/slackvars).tolist() +  # slackvars > 1
TypeError: unsupported operand type(s) for /: 'int' and 'PosyArray'

----------------------------------------------------------------------
Ran 88 tests in 1.007s

FAILED (errors=5)
'''

**Comment by bqpd** [comment] 2015-09-03 16:51
Deleting as duplicate of #386

**Closed by bqpd** 2015-09-03 16:51 UTC
